---
- name: Import Elasticsearch GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    update_cache: yes

- name: Install Elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    state: present

- name: Update Elasticsearch configuration
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0644'
  notify:
    - restart elasticsearch

- name: Ensure Elasticsearch is enabled and running
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: yes
    state: started
