---
- name: Ensure Python3 and pip are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install psycopg2 Python library
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present

- name: Import the repository signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    update_cache: yes

- name: Install PostgreSQL 15
  ansible.builtin.apt:
    name: postgresql-15
    state: present
    update_cache: yes

- name: Ensure the PostgreSQL service is running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create PostgreSQL user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
    state: present

- name: Create PostgreSQL database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    # encoding: 'UTF8'
    # lc_collate: 'en_US.UTF-8'
    # lc_ctype: 'en_US.UTF-8'
    # template: 'template0'
    state: present

- name: Create schema in PostgreSQL database
  become: yes
  become_user: postgres
  postgresql_schema:
    name: "{{ db_schema }}"
    database: "{{ db_name }}"
    state: present
