---
- name: Add repository for PHP 8.2
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: Install PHP 8.2 and modules
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php8.2-fpm
    - php8.2-amqp
    - php8.2-apcu
    - php8.2-common
    - php8.2-calendar
    - php8.2-ctype
    - php8.2-curl
    - php8.2-dom
    - php8.2-exif
    - php8.2-ffi
    - php8.2-fileinfo
    - php8.2-ftp
    - php8.2-gettext
    - php8.2-iconv
    - php8.2-intl
    - php8.2-phpdbg
    - php8.2-mbstring
    - php8.2-mysqli
    - php8.2-pdo
    - php8.2-pdo-mysql
    - php8.2-pdo-pgsql
    - php8.2-pdo-sqlite
    - php8.2-pgsql
    - php8.2-phar
    - php8.2-posix
    - php8.2-readline
    - php8.2-shmop
    - php8.2-simplexml
    - php8.2-soap
    - php8.2-sockets
    - php8.2-sqlite3
    - php8.2-sysvmsg
    - php8.2-sysvsem
    - php8.2-sysvshm
    - php8.2-tokenizer
    - php8.2-xml
    - php8.2-xmlreader
    - php8.2-xmlwriter
    - php8.2-xsl
    - php8.2-opcache
    # - php8.2-json included in php8.2-phpdbg
    # - php8.2-filter
    # - php8.2-hash
    # - php8.2-openssl
    # - php8.2-pcntl
    # - php8.2-reflection
    # - php8.2-session
    # - php8.2-sodium
    # - php8.2-zlib
