---
- name: Check if the destination is a Git repository
  ansible.builtin.stat:
    path: "{{ deploy_path }}/.git"
  register: git_repo

- name: Update existing Git repository
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ deploy_path }}"
    version: "{{ repo_branch }}"
    update: yes
  when: git_repo.stat.exists

- name: Clone Git repository
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ deploy_path }}"
    version: "{{ repo_branch }}"
  when: not git_repo.stat.exists
  register: git_result

# - name: Update configuration files
#   ansible.builtin.template:
#     src: "{{ item.src }}"
#     dest: "{{ deploy_path }}/{{ item.dest }}"
#   with_items:
#     - { src: 'db_config.php.j2', dest: 'config/db_config.php' }
#   when: git_result is defined and git_result.changed

# - name: Restart php-fpm
#   ansible.builtin.systemd:
#     name: php{{ php_version }}-fpm
#     state: restarted
#   when: git_result is defined and git_result.changed
#   notify: restart nginx

- name: Ensure nginx is enabled and running
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
  when: git_result is defined and git_result.changed
